name: 'deploy happykit docs'
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: build-dist
      - run: yarn install
      - run: yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          ACCESS_TOKEN: 4f67397c7481cc49248814732a6d788e0021d0db
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
